env: "local" # local,dev,prod

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

database:
  host: "postgres"
  port: 5432
  username: "Marat"
  password: 1234
  db_name:  "Test"